on:  
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Check order of markdown list items
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Lint markdown lists
        uses: ClydeDz/markdown-list-linter@main
        with:
          file: ./README.md
          fail-on-error: true
